import turtle
#Blue Hexagon
turtle.penup()
turtle.pensize(5)
turtle.color("blue")
turtle.pendown()
turtle.circle(100, 360, 6)
#Green Hexagon
turtle.penup()
turtle.setheading(270)
turtle.color("green")
turtle.pendown()
turtle.circle(100, 360, 6)
#Yellow Hexagon
turtle.penup()
turtle.setheading(180)
turtle.color("yellow")
turtle.pendown()
turtle.circle(100, 360, 6)
# #Red Hexagon
turtle.penup()
turtle.setheading(90)
turtle.color("red")
turtle.pendown()
turtle.circle(100, 360, 6)
turtle.reset()



#UK FLAG
area = turtle.Screen()
area.setup(width = 700, height = 400)
turtle.ht()
def make_rectangle(length,width):
    turtle.pendown()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(width)
def make_parallelogram(xlen,ylen,angle):
    diaglen = ((xlen**2)+(ylen**2))**0.5
    turtle.pendown()
    turtle.forward(xlen)
    turtle.left(angle)
    turtle.forward(diaglen)
    turtle.left(180-angle)
    turtle.forward(xlen)
    turtle.left(angle)
    turtle.forward(diaglen)
def make_parallelogram_backward(xlen,ylen,angle):
    diaglen = ((xlen**2)+(ylen**2))**0.5
    turtle.pendown()
    turtle.forward(xlen)
    turtle.left(180-angle)
    turtle.forward(diaglen)
    turtle.left(angle)
    turtle.forward(xlen)
    turtle.left(180-angle)
    turtle.forward(diaglen)
def make_triangle_upward_right(oppo,adja,hypo): #3-4-5 Triangle
    turtle.pendown()
    turtle.forward(adja)
    turtle.left(143)
    turtle.forward(hypo)
    turtle.left(127)
    turtle.forward(oppo)
def make_triangle_downward_right(oppo,adja,hypo): #3-4-5 Triangle
    turtle.pendown()
    turtle.forward(adja)
    turtle.right(143)
    turtle.forward(hypo)
    turtle.right(127)
    turtle.forward(oppo)
def make_triangle_downward_left(oppo,adja,hypo): #3-4-5 Triangle
    turtle.pendown()
    turtle.forward(adja)
    turtle.right(90)
    turtle.forward(oppo)
    turtle.right(127)
    turtle.forward(hypo)
def make_triangle_upward_left(oppo,adja,hypo): #3-4-5 Triangle
    turtle.pendown()
    turtle.forward(adja)
    turtle.left(90)
    turtle.forward(oppo)
    turtle.left(127)
    turtle.forward(hypo)
def set_heading_color(color):
    turtle.setheading(0)
    if color == "white":
        turtle.color("#ffffff")
    elif color == "blue":
        turtle.color("#012169")
    elif color == "red":
        turtle.color("#c8102e")
    elif color == "dark green":
        turtle.color("dark green")
    else:
        pass
        

turtle.speed(10)
turtle.penup()
#Make flag large border (700x400)
turtle.goto(-350,-200)
turtle.pencolor("black")
make_rectangle(700,400)
#Make RED CROSS
turtle.goto(-35,-200)
set_heading_color("red")
turtle.begin_fill()
make_rectangle(70,400)
turtle.penup()
turtle.goto(-350,35)
turtle.setheading(270)
make_rectangle(70,700)
turtle.end_fill()
#Make pattern top-left
turtle.penup()
turtle.goto(-350,60)
set_heading_color("white")
make_rectangle(290,140)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_upward_right(105,135,175)
turtle.end_fill()
turtle.penup()
turtle.goto(-178,60)
set_heading_color("red")
turtle.begin_fill()
make_parallelogram_backward(55,260,37)
turtle.end_fill()
turtle.penup()
turtle.goto(-240,200)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_downward_left(129,172,215)
turtle.end_fill()
#Make pattern bottom-left
turtle.penup()
turtle.goto(-350,-60)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_downward_right(105,135,175)
turtle.end_fill()
turtle.penup()
turtle.goto(-350,-200)
set_heading_color("red")
turtle.begin_fill()
make_parallelogram(55,223,37)
turtle.end_fill()
turtle.penup()
turtle.goto(-240,-200)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_upward_left(129,172,215)
turtle.end_fill()
#Make pattern top-right
turtle.penup()
turtle.goto(68,200)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_downward_right(129,172,215)
turtle.end_fill()
turtle.penup()
turtle.goto(88,60)
set_heading_color("red")
turtle.begin_fill()
make_parallelogram(55,223,37)
turtle.end_fill()
turtle.penup()
turtle.goto(215,60)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_upward_left(105,135,175)
turtle.end_fill()
turtle.penup()
#Make pattern bottom-right
turtle.goto(68,-200)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_upward_right(129,172,215)
turtle.end_fill()
turtle.goto(277,-200)
set_heading_color("red")
turtle.begin_fill()
make_parallelogram_backward(55,218,37)
turtle.end_fill()
turtle.penup()
turtle.goto(215,-60)
set_heading_color("blue")
turtle.begin_fill()
make_triangle_downward_left(105,135,175)
turtle.end_fill()
turtle.reset()




#Traffic light
turtle.penup()
turtle.goto(0,-170)
turtle.setheading(45)
turtle.color("#f4d623")
turtle.begin_fill()
make_rectangle(250,250)
turtle.end_fill()
turtle.color("black")
turtle.penup()
turtle.goto(0,-160)
turtle.setheading(45)
turtle.pensize(2)
make_rectangle(235,235)
turtle.pensize(1)
turtle.penup()
turtle.goto(-25,-70)
set_heading_color("black")
turtle.begin_fill()
make_rectangle(50,140)
turtle.end_fill()
turtle.penup()
turtle.goto(0,30)
turtle.pendown()
turtle.setheading(0)
turtle.color("#bf1407")
turtle.begin_fill()
turtle.circle(18)
turtle.end_fill()
turtle.penup()
turtle.goto(0,-18)
turtle.color("#fcfd5d")
turtle.pendown()
turtle.setheading(0)
turtle.begin_fill()
turtle.circle(18)
turtle.end_fill()
turtle.penup()
turtle.goto(0,-66)
set_heading_color("dark green")
turtle.pendown()
turtle.begin_fill()
turtle.circle(18)
turtle.end_fill()
turtle.done()




